// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWord(arg1) {
  return window['go']['main']['App']['AddWord'](arg1);
}

export function DeleteWord(arg1) {
  return window['go']['main']['App']['DeleteWord'](arg1);
}

export function ExportWords(arg1) {
  return window['go']['main']['App']['ExportWords'](arg1);
}

export function GetAllWords() {
  return window['go']['main']['App']['GetAllWords']();
}

export function GetLearningStats() {
  return window['go']['main']['App']['GetLearningStats']();
}

export function GetNewWordsToLearn(arg1) {
  return window['go']['main']['App']['GetNewWordsToLearn'](arg1);
}

export function GetPronunciation(arg1) {
  return window['go']['main']['App']['GetPronunciation'](arg1);
}

export function GetWordByID(arg1) {
  return window['go']['main']['App']['GetWordByID'](arg1);
}

export function GetWordImage(arg1) {
  return window['go']['main']['App']['GetWordImage'](arg1);
}

export function GetWordsForReview() {
  return window['go']['main']['App']['GetWordsForReview']();
}

export function ImportWords(arg1) {
  return window['go']['main']['App']['ImportWords'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2, arg3);
}

export function SaveWordImageFromURL(arg1, arg2) {
  return window['go']['main']['App']['SaveWordImageFromURL'](arg1, arg2);
}

export function UpdateWord(arg1) {
  return window['go']['main']['App']['UpdateWord'](arg1);
}

export function UpdateWordAfterReview(arg1, arg2) {
  return window['go']['main']['App']['UpdateWordAfterReview'](arg1, arg2);
}
