// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddWord(arg1:models.Word):Promise<models.Word>;

export function DeleteWord(arg1:number):Promise<void>;

export function ExportWords(arg1:string):Promise<void>;

export function GetAllWords():Promise<Array<models.Word>>;

export function GetLearningStats():Promise<Record<string, number>>;

export function GetNewWordsToLearn(arg1:number):Promise<Array<models.Word>>;

export function GetPronunciation(arg1:string):Promise<string>;

export function GetWordByID(arg1:number):Promise<models.Word>;

export function GetWordImage(arg1:string):Promise<string>;

export function GetWordsForReview():Promise<Array<models.Word>>;

export function ImportWords(arg1:string):Promise<void>;

export function OpenFileDialog(arg1:string,arg2:Record<string, Array<string>>):Promise<string>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:Record<string, Array<string>>):Promise<string>;

export function SaveWordImageFromURL(arg1:string,arg2:string):Promise<string>;

export function UpdateWord(arg1:models.Word):Promise<void>;

export function UpdateWordAfterReview(arg1:number,arg2:number):Promise<void>;
